# Generated by Django 5.2.5 on 2025-08-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_private_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
