# Generated by Django 5.2.5 on 2025-08-24 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='views_count',
        ),
    ]
